steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        set -x && \
        gcloud compute ssh cloudbuild@backend-instance --zone=us-central1-a --command='sudo /bin/sh /home/ampelishko/pull.sh'
